# See
#   - https://github.com/netbox-community/netbox-docker/blob/release/README.md
#   - https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins
# git clone https://github.com/netbox-community/netbox-docker/
# Edit files
# docker-compose build --no-cache
# docker-compose up -d

services:
  netbox:
    ports:
      - 8000:8080
    build:
      context: ${NETMAPPER_PATH:-../NetMapper}
      dockerfile: docker/Dockerfile-Plugins
    volumes:
      - ${NETMAPPER_PATH:-../NetMapper}/docker/configuration/plugins.py:/etc/netbox/config/plugins.py:ro
    image: netbox:${NETMAPPER_IMAGE_TAG:-latest-plugins}
  netbox-worker:
    image: netbox:${NETMAPPER_IMAGE_TAG:-latest-plugins}
    build:
      context: ${NETMAPPER_PATH:-../NetMapper}
      dockerfile: docker/Dockerfile-Plugins
    volumes:
      - ${NETMAPPER_PATH:-../NetMapper}/docker/configuration/plugins.py:/etc/netbox/config/plugins.py:ro
